//
//  CharacterSets.swift
//  Tateru
//
//  Created by Tiago Carvalho on 1/22/25.
//


import Foundation

struct CharacterSets {
    // Content remains the same as before
    static let hiragana: [Character] = [
        // Vowels (あ行, A-row)
        Character(
            symbol: "あ",
            romaji: "a",
            type: .hiragana,
            examples: ["あい (ai) - love", "あめ (ame) - rain"],
            pronunciation: "like 'a' in 'father'",
            strokeOrder: "1. horizontal\n2. curved line",
            notes: "Basic vowel",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "い",
            romaji: "i",
            type: .hiragana,
            examples: ["いぬ (inu) - dog", "いけ (ike) - pond"],
            pronunciation: "like 'ee' in 'see'",
            strokeOrder: "1. vertical line\n2. sweep right",
            notes: "Basic vowel",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "う",
            romaji: "u",
            type: .hiragana,
            examples: ["うみ (umi) - sea", "うた (uta) - song"],
            pronunciation: "like 'oo' in 'boot'",
            strokeOrder: "1. curved vertical\n2. curved horizontal",
            notes: "Basic vowel",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "え",
            romaji: "e",
            type: .hiragana,
            examples: ["えき (eki) - station", "えいが (eiga) - movie"],
            pronunciation: "like 'e' in 'pet'",
            strokeOrder: "1. horizontal\n2. vertical\n3. hook",
            notes: "Basic vowel",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "お",
            romaji: "o",
            type: .hiragana,
            examples: ["おかし (okashi) - snack", "おと (oto) - sound"],
            pronunciation: "like 'o' in 'go'",
            strokeOrder: "1. horizontal curve\n2. vertical sweep",
            notes: "Basic vowel",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        
        // K-row (か行)
        Character(
            symbol: "か",
            romaji: "ka",
            type: .hiragana,
            examples: ["かばん (kaban) - bag", "かみ (kami) - paper"],
            pronunciation: "like 'ka' in 'karma'",
            strokeOrder: "1. horizontal\n2. vertical\n3. diagonal",
            notes: "Changes to が (ga) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "き",
            romaji: "ki",
            type: .hiragana,
            examples: ["きっぷ (kippu) - ticket", "きた (kita) - north"],
            pronunciation: "like 'key'",
            strokeOrder: "1. vertical\n2. horizontal\n3. sweep",
            notes: "Changes to ぎ (gi) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "く",
            romaji: "ku",
            type: .hiragana,
            examples: ["くに (kuni) - country", "くも (kumo) - cloud"],
            pronunciation: "like 'coo'",
            strokeOrder: "1. top angle\n2. bottom curve",
            notes: "Changes to ぐ (gu) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "け",
            romaji: "ke",
            type: .hiragana,
            examples: ["けいこ (keiko) - practice", "けさ (kesa) - this morning"],
            pronunciation: "like 'ke' in 'kettle'",
            strokeOrder: "1. vertical\n2. diagonal\n3. horizontal",
            notes: "Changes to げ (ge) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "こ",
            romaji: "ko",
            type: .hiragana,
            examples: ["こども (kodomo) - child", "ここ (koko) - here"],
            pronunciation: "like 'ko' in 'koto'",
            strokeOrder: "1. horizontal\n2. vertical",
            notes: "Changes to ご (go) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        
        // S-row (さ行)
        Character(
            symbol: "さ",
            romaji: "sa",
            type: .hiragana,
            examples: ["さくら (sakura) - cherry blossom", "さる (saru) - monkey"],
            pronunciation: "like 'sa' in 'saw'",
            strokeOrder: "1. horizontal\n2. diagonal stroke\n3. short stroke",
            notes: "Changes to ざ (za) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "し",
            romaji: "shi",
            type: .hiragana,
            examples: ["しま (shima) - island", "しろ (shiro) - white/castle"],
            pronunciation: "like 'she'",
            strokeOrder: "1. diagonal\n2. vertical sweep",
            notes: "Changes to じ (ji) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "す",
            romaji: "su",
            type: .hiragana,
            examples: ["すし (sushi) - sushi", "すき (suki) - like"],
            pronunciation: "like 'su' in 'super'",
            strokeOrder: "1. loop\n2. horizontal",
            notes: "Changes to ず (zu) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "せ",
            romaji: "se",
            type: .hiragana,
            examples: ["せんせい (sensei) - teacher", "せかい (sekai) - world"],
            pronunciation: "like 'se' in 'set'",
            strokeOrder: "1. diagonal\n2. vertical\n3. horizontal",
            notes: "Changes to ぜ (ze) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "そ",
            romaji: "so",
            type: .hiragana,
            examples: ["そら (sora) - sky", "そと (soto) - outside"],
            pronunciation: "like 'so' in 'soda'",
            strokeOrder: "1. horizontal\n2. vertical curve",
            notes: "Changes to ぞ (zo) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        
        // T-row (た行)
        Character(
            symbol: "た",
            romaji: "ta",
            type: .hiragana,
            examples: ["たべる (taberu) - to eat", "たかい (takai) - high/expensive"],
            pronunciation: "like 'ta' in 'top'",
            strokeOrder: "1. horizontal\n2. vertical\n3. diagonal",
            notes: "Changes to だ (da) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "ち",
            romaji: "chi",
            type: .hiragana,
            examples: ["ちず (chizu) - map", "ちかい (chikai) - close/near"],
            pronunciation: "like 'chi' in 'cheese'",
            strokeOrder: "1. diagonal\n2. vertical\n3. sweep",
            notes: "Changes to ぢ (ji) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "つ",
            romaji: "tsu",
            type: .hiragana,
            examples: ["つき (tsuki) - moon", "つくえ (tsukue) - desk"],
            pronunciation: "like 'ts' in 'cats' + 'oo'",
            strokeOrder: "1. curve\n2. diagonal sweep",
            notes: "Changes to づ (zu) with dakuten. Also used small っ for gemination",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "て",
            romaji: "te",
            type: .hiragana,
            examples: ["てがみ (tegami) - letter", "てんき (tenki) - weather"],
            pronunciation: "like 'te' in 'tell'",
            strokeOrder: "1. horizontal\n2. vertical curve",
            notes: "Changes to で (de) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "と",
            romaji: "to",
            type: .hiragana,
            examples: ["とり (tori) - bird", "とけい (tokei) - clock/watch"],
            pronunciation: "like 'to' in 'toe'",
            strokeOrder: "1. vertical curve\n2. horizontal sweep",
            notes: "Changes to ど (do) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        
        // N-row (な行)
        Character(
            symbol: "な",
            romaji: "na",
            type: .hiragana,
            examples: ["なまえ (namae) - name", "なつ (natsu) - summer"],
            pronunciation: "like 'na' in 'not'",
            strokeOrder: "1. horizontal\n2. vertical\n3. diagonal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "に",
            romaji: "ni",
            type: .hiragana,
            examples: ["にく (niku) - meat", "にわ (niwa) - garden"],
            pronunciation: "like 'nee'",
            strokeOrder: "1. horizontal\n2. vertical\n3. diagonal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "ぬ",
            romaji: "nu",
            type: .hiragana,
            examples: ["ぬま (numa) - swamp", "ぬの (nuno) - cloth"],
            pronunciation: "like 'noo'",
            strokeOrder: "1. curve\n2. horizontal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "ね",
            romaji: "ne",
            type: .hiragana,
            examples: ["ねこ (neko) - cat", "ねつ (netsu) - fever"],
            pronunciation: "like 'ne' in 'net'",
            strokeOrder: "1. curve\n2. diagonal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "の",
            romaji: "no",
            type: .hiragana,
            examples: ["のみもの (nomimono) - drink", "のる (noru) - to ride"],
            pronunciation: "like 'no' in 'note'",
            strokeOrder: "1. curved stroke",
            notes: "Also used as a possessive particle",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        
        // H-row (は行)
        Character(
            symbol: "は",
            romaji: "ha",
            type: .hiragana,
            examples: ["はな (hana) - flower", "はし (hashi) - chopsticks/bridge"],
            pronunciation: "like 'ha' in 'hot'",
            strokeOrder: "1. horizontal\n2. vertical\n3. diagonal",
            notes: "Changes to ば (ba) with dakuten, ぱ (pa) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "ひ",
            romaji: "hi",
            type: .hiragana,
            examples: ["ひと (hito) - person", "ひる (hiru) - afternoon"],
            pronunciation: "like 'he' in 'he'",
            strokeOrder: "1. vertical\n2. diagonal sweep",
            notes: "Changes to び (bi) with dakuten, ぴ (pi) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "ふ",
            romaji: "fu",
            type: .hiragana,
            examples: ["ふゆ (fuyu) - winter", "ふく (fuku) - clothes"],
            pronunciation: "like 'fu' (between 'fu' and 'hu')",
            strokeOrder: "1. diagonal\n2. horizontal",
            notes: "Changes to ぶ (bu) with dakuten, ぷ (pu) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "へ",
            romaji: "he",
            type: .hiragana,
            examples: ["へや (heya) - room", "へび (hebi) - snake"],
            pronunciation: "like 'he' in 'help'",
            strokeOrder: "1. curved stroke",
            notes: "Changes to べ (be) with dakuten, ぺ (pe) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "ほ",
            romaji: "ho",
            type: .hiragana,
            examples: ["ほん (hon) - book", "ほし (hoshi) - star"],
            pronunciation: "like 'ho' in 'hope'",
            strokeOrder: "1. vertical\n2. horizontal\n3. diagonal",
            notes: "Changes to ぼ (bo) with dakuten, ぽ (po) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        
        // M-row (ま行)
        Character(
            symbol: "ま",
            romaji: "ma",
            type: .hiragana,
            examples: ["まど (mado) - window", "まち (machi) - town"],
            pronunciation: "like 'ma' in 'mall'",
            strokeOrder: "1. horizontal\n2. vertical\n3. diagonal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "み",
            romaji: "mi",
            type: .hiragana,
            examples: ["みず (mizu) - water", "みせ (mise) - shop"],
            pronunciation: "like 'me' in 'me'",
            strokeOrder: "1. vertical\n2. diagonal\n3. horizontal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "む",
            romaji: "mu",
            type: .hiragana,
            examples: ["むし (mushi) - insect", "むら (mura) - village"],
            pronunciation: "like 'moo'",
            strokeOrder: "1. top curve\n2. bottom curve",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        Character(
            symbol: "め",
            romaji: "me",
            type: .hiragana,
            examples: ["めがね (megane) - glasses", "あめ (ame) - rain"],
            pronunciation: "like 'me' in 'met'",
            strokeOrder: "1. vertical curve\n2. horizontal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil),
        
        // H-row (は行)
        Character(
            symbol: "は",
            romaji: "ha",
            type: .hiragana,
            examples: ["はな (hana) - flower", "はし (hashi) - chopsticks/bridge"],
            pronunciation: "like 'ha' in 'hot'",
            strokeOrder: "1. horizontal\n2. vertical\n3. diagonal",
            notes: "Changes to ば (ba) with dakuten, ぱ (pa) with handakuten. Also used as topic particle は (wa)",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ひ",
            romaji: "hi",
            type: .hiragana,
            examples: ["ひと (hito) - person", "ひる (hiru) - afternoon/daytime"],
            pronunciation: "like 'hee'",
            strokeOrder: "1. vertical\n2. diagonal sweep",
            notes: "Changes to び (bi) with dakuten, ぴ (pi) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ふ",
            romaji: "fu",
            type: .hiragana,
            examples: ["ふね (fune) - boat", "ふゆ (fuyu) - winter"],
            pronunciation: "like 'who'",
            strokeOrder: "1. diagonal\n2. horizontal",
            notes: "Changes to ぶ (bu) with dakuten, ぷ (pu) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "へ",
            romaji: "he",
            type: .hiragana,
            examples: ["へや (heya) - room", "へび (hebi) - snake"],
            pronunciation: "like 'he' in 'help'",
            strokeOrder: "1. curved stroke",
            notes: "Changes to べ (be) with dakuten, ぺ (pe) with handakuten. As particle へ is pronounced 'e'",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ほ",
            romaji: "ho",
            type: .hiragana,
            examples: ["ほん (hon) - book", "ほし (hoshi) - star"],
            pronunciation: "like 'ho' in 'hope'",
            strokeOrder: "1. vertical\n2. horizontal\n3. diagonal",
            notes: "Changes to ぼ (bo) with dakuten, ぽ (po) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // M-row (ま行)
        Character(
            symbol: "ま",
            romaji: "ma",
            type: .hiragana,
            examples: ["まち (machi) - town", "まど (mado) - window"],
            pronunciation: "like 'ma' in 'mall'",
            strokeOrder: "1. horizontal\n2. vertical\n3. diagonal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "み",
            romaji: "mi",
            type: .hiragana,
            examples: ["みず (mizu) - water", "みみ (mimi) - ear"],
            pronunciation: "like 'me' in 'me'",
            strokeOrder: "1. vertical\n2. diagonal\n3. horizontal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "む",
            romaji: "mu",
            type: .hiragana,
            examples: ["むし (mushi) - insect", "むら (mura) - village"],
            pronunciation: "like 'moo'",
            strokeOrder: "1. top curve\n2. bottom curve",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "め",
            romaji: "me",
            type: .hiragana,
            examples: ["め (me) - eye", "あめ (ame) - rain"],
            pronunciation: "like 'me' in 'met'",
            strokeOrder: "1. vertical curve\n2. horizontal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "も",
            romaji: "mo",
            type: .hiragana,
            examples: ["もの (mono) - thing", "もり (mori) - forest"],
            pronunciation: "like 'mo' in 'more'",
            strokeOrder: "1. vertical\n2. horizontal\n3. diagonal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // Y-row (や行)
        Character(
            symbol: "や",
            romaji: "ya",
            type: .hiragana,
            examples: ["やま (yama) - mountain", "やさい (yasai) - vegetable"],
            pronunciation: "like 'ya' in 'yard'",
            strokeOrder: "1. diagonal\n2. vertical sweep",
            notes: "Also used as small ゃ for combining sounds",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ゆ",
            romaji: "yu",
            type: .hiragana,
            examples: ["ゆき (yuki) - snow", "ゆび (yubi) - finger"],
            pronunciation: "like 'you'",
            strokeOrder: "1. loop\n2. diagonal",
            notes: "Also used as small ゅ for combining sounds",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "よ",
            romaji: "yo",
            type: .hiragana,
            examples: ["よる (yoru) - night", "よむ (yomu) - to read"],
            pronunciation: "like 'yo' in 'yo-yo'",
            strokeOrder: "1. diagonal\n2. horizontal",
            notes: "Also used as small ょ for combining sounds",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // R-row (ら行)
        Character(
            symbol: "ら",
            romaji: "ra",
            type: .hiragana,
            examples: ["らいねん (rainen) - next year", "らく (raku) - comfortable"],
            pronunciation: "between 'la' and 'ra'",
            strokeOrder: "1. diagonal\n2. curve",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "り",
            romaji: "ri",
            type: .hiragana,
            examples: ["りんご (ringo) - apple", "おり (ori) - cage"],
            pronunciation: "between 'li' and 'ri'",
            strokeOrder: "1. vertical\n2. diagonal sweep",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "る",
            romaji: "ru",
            type: .hiragana,
            examples: ["るす (rusu) - absent", "かる (karu) - to cut"],
            pronunciation: "between 'lu' and 'ru'",
            strokeOrder: "1. loop\n2. diagonal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "れ",
            romaji: "re",
            type: .hiragana,
            examples: ["れきし (rekishi) - history", "これ (kore) - this"],
            pronunciation: "between 'le' and 're'",
            strokeOrder: "1. diagonal\n2. curve",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ろ",
            romaji: "ro",
            type: .hiragana,
            examples: ["ろく (roku) - six", "ころ (koro) - time/about"],
            pronunciation: "between 'lo' and 'ro'",
            strokeOrder: "1. vertical\n2. diagonal\n3. horizontal",
            notes: nil,
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // W-row (わ行)
        Character(
            symbol: "わ",
            romaji: "wa",
            type: .hiragana,
            examples: ["わたし (watashi) - I", "かわ (kawa) - river"],
            pronunciation: "like 'wa' in 'want'",
            strokeOrder: "1. hook\n2. curve",
            notes: "Also used as topic marking particle",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "を",
            romaji: "wo",
            type: .hiragana,
            examples: ["Object marker particle"],
            pronunciation: "like 'o' (pronounced 'o' when used as particle)",
            strokeOrder: "1. hook\n2. sweep",
            notes: "Only used as object marking particle in modern Japanese",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // N (ん)
        Character(
            symbol: "ん",
            romaji: "n",
            type: .hiragana,
            examples: ["ほん (hon) - book", "せんせい (sensei) - teacher"],
            pronunciation: "like 'n' in 'sin'",
            strokeOrder: "1. curve\n2. diagonal",
            notes: "Only consonant that can end a word in Japanese",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        )
    ]
    
    
    static let katakana: [Character] = [
        // Vowels
        Character(
            symbol: "ア",
            romaji: "a",
            type: .katakana,
            examples: ["アイス (aisu) - ice cream", "アメリカ (amerika) - America"],
            pronunciation: "like 'a' in 'father'",
            strokeOrder: "1. diagonal down\n2. diagonal up",
            notes: "Basic vowel",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "イ",
            romaji: "i",
            type: .katakana,
            examples: ["イギリス (igirisu) - England", "インド (indo) - India"],
            pronunciation: "like 'ee' in 'see'",
            strokeOrder: "1. vertical line\n2. diagonal line",
            notes: "Basic vowel",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ウ",
            romaji: "u",
            type: .katakana,
            examples: ["ウール (ūru) - wool", "ウサギ (usagi) - rabbit"],
            pronunciation: "like 'oo' in 'boot'",
            strokeOrder: "1. vertical curve\n2. small curve right",
            notes: "Basic vowel",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "エ",
            romaji: "e",
            type: .katakana,
            examples: ["エレベーター (erebētā) - elevator", "エビ (ebi) - shrimp"],
            pronunciation: "like 'e' in 'pet'",
            strokeOrder: "1. horizontal\n2. vertical\n3. middle horizontal",
            notes: "Basic vowel",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "オ",
            romaji: "o",
            type: .katakana,
            examples: ["オレンジ (orenji) - orange", "オフィス (ofisu) - office"],
            pronunciation: "like 'o' in 'go'",
            strokeOrder: "1. horizontal\n2. vertical",
            notes: "Basic vowel",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // K-row starts
        Character(
            symbol: "カ",
            romaji: "ka",
            type: .katakana,
            examples: ["カメラ (kamera) - camera", "カレー (karē) - curry"],
            pronunciation: "like 'ka' in 'karma'",
            strokeOrder: "1. vertical\n2. diagonal",
            notes: "Changes to ガ (ga) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "キ",
            romaji: "ki",
            type: .katakana,
            examples: ["キーボード (kībōdo) - keyboard", "キス (kisu) - kiss"],
            pronunciation: "like 'key'",
            strokeOrder: "1. vertical\n2. cross strokes",
            notes: "Changes to ギ (gi) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ク",
            romaji: "ku",
            type: .katakana,
            examples: ["クラス (kurasu) - class", "クリスマス (kurisumasu) - Christmas"],
            pronunciation: "like 'ku' in 'kook'",
            strokeOrder: "1. angle stroke",
            notes: "Changes to グ (gu) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ケ",
            romaji: "ke",
            type: .katakana,
            examples: ["ケーキ (kēki) - cake", "ケース (kēsu) - case"],
            pronunciation: "like 'ke' in 'kettle'",
            strokeOrder: "1. vertical\n2. diagonal hook",
            notes: "Changes to ゲ (ge) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "コ",
            romaji: "ko",
            type: .katakana,
            examples: ["コーヒー (kōhī) - coffee", "コピー (kopī) - copy"],
            pronunciation: "like 'ko' in 'koto'",
            strokeOrder: "1. horizontal\n2. vertical",
            notes: "Changes to ゴ (go) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        // S-row (サ行)
        Character(
            symbol: "サ",
            romaji: "sa",
            type: .katakana,
            examples: ["サイト (saito) - website", "サラダ (sarada) - salad"],
            pronunciation: "like 'sa' in 'saga'",
            strokeOrder: "1. horizontal\n2. diagonal cross",
            notes: "Changes to ザ (za) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "シ",
            romaji: "shi",
            type: .katakana,
            examples: ["シャツ (shatsu) - shirt", "シャワー (shawā) - shower"],
            pronunciation: "like 'shi' in 'sheet'",
            strokeOrder: "1. diagonal sweep\n2. short diagonal",
            notes: "Changes to ジ (ji) with dakuten. Often used in しゃ (sha), しゅ (shu), しょ (sho) combinations",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ス",
            romaji: "su",
            type: .katakana,
            examples: ["スポーツ (supōtsu) - sports", "スマホ (sumaho) - smartphone"],
            pronunciation: "like 'su' in 'super'",
            strokeOrder: "1. diagonal\n2. vertical sweep",
            notes: "Changes to ズ (zu) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "セ",
            romaji: "se",
            type: .katakana,
            examples: ["セーター (sētā) - sweater", "セット (setto) - set"],
            pronunciation: "like 'se' in 'set'",
            strokeOrder: "1. horizontal\n2. vertical with hook",
            notes: "Changes to ゼ (ze) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ソ",
            romaji: "so",
            type: .katakana,
            examples: ["ソファー (sofā) - sofa", "ソース (sōsu) - sauce"],
            pronunciation: "like 'so' in 'soda'",
            strokeOrder: "1. diagonal sweep",
            notes: "Changes to ゾ (zo) with dakuten. Be careful not to confuse with ン (n)",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // T-row (タ行)
        Character(
            symbol: "タ",
            romaji: "ta",
            type: .katakana,
            examples: ["タクシー (takushī) - taxi", "タオル (taoru) - towel"],
            pronunciation: "like 'ta' in 'top'",
            strokeOrder: "1. horizontal\n2. vertical with hook",
            notes: "Changes to ダ (da) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "チ",
            romaji: "chi",
            type: .katakana,
            examples: ["チケット (chiketto) - ticket", "チーズ (chīzu) - cheese"],
            pronunciation: "like 'chi' in 'cheese'",
            strokeOrder: "1. vertical\n2. horizontal sweep",
            notes: "Changes to ヂ (ji) with dakuten. Often used in チャ (cha), チュ (chu), チョ (cho) combinations",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ツ",
            romaji: "tsu",
            type: .katakana,
            examples: ["ツアー (tsuā) - tour", "ツナ (tsuna) - tuna"],
            pronunciation: "like 'ts' in 'cats' + 'oo'",
            strokeOrder: "1. diagonal sweep\n2. short diagonal",
            notes: "Changes to ヅ (zu) with dakuten. Small ッ used for consonant doubling",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "テ",
            romaji: "te",
            type: .katakana,
            examples: ["テスト (tesuto) - test", "テーブル (tēburu) - table"],
            pronunciation: "like 'te' in 'tell'",
            strokeOrder: "1. horizontal\n2. vertical hook",
            notes: "Changes to デ (de) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ト",
            romaji: "to",
            type: .katakana,
            examples: ["トマト (tomato) - tomato", "トースト (tōsuto) - toast"],
            pronunciation: "like 'to' in 'toe'",
            strokeOrder: "1. vertical\n2. horizontal hook",
            notes: "Changes to ド (do) with dakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        // N-row (ナ行)
        Character(
            symbol: "ナ",
            romaji: "na",
            type: .katakana,
            examples: ["ナイフ (naifu) - knife", "ナンバー (nanbā) - number"],
            pronunciation: "like 'na' in 'not'",
            strokeOrder: "1. diagonal\n2. vertical stroke",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ニ",
            romaji: "ni",
            type: .katakana,
            examples: ["ニュース (nyūsu) - news", "ニックネーム (nikkunēmu) - nickname"],
            pronunciation: "like 'ni' in 'need'",
            strokeOrder: "1. horizontal\n2. horizontal",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ヌ",
            romaji: "nu",
            type: .katakana,
            examples: ["ヌードル (nūdoru) - noodle", "メヌー (menyū) - menu"],
            pronunciation: "like 'nu' in 'new'",
            strokeOrder: "1. curve\n2. diagonal",
            notes: "Less common in loan words",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ネ",
            romaji: "ne",
            type: .katakana,
            examples: ["ネクタイ (nekutai) - necktie", "ネット (netto) - internet/net"],
            pronunciation: "like 'ne' in 'net'",
            strokeOrder: "1. diagonal curve\n2. diagonal",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ノ",
            romaji: "no",
            type: .katakana,
            examples: ["ノート (nōto) - notebook", "ピアノ (piano) - piano"],
            pronunciation: "like 'no' in 'note'",
            strokeOrder: "1. diagonal sweep",
            notes: "No dakuten form. Similar to the hiragana の but more angular",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // H-row (ハ行) first half
        Character(
            symbol: "ハ",
            romaji: "ha",
            type: .katakana,
            examples: ["ハンバーガー (hanbāgā) - hamburger", "ハロウィン (harowin) - Halloween"],
            pronunciation: "like 'ha' in 'hot'",
            strokeOrder: "1. diagonal\n2. diagonal",
            notes: "Changes to バ (ba) with dakuten, パ (pa) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ヒ",
            romaji: "hi",
            type: .katakana,
            examples: ["ヒーター (hītā) - heater", "ヒント (hinto) - hint"],
            pronunciation: "like 'he' in 'he'",
            strokeOrder: "1. vertical\n2. diagonal sweep",
            notes: "Changes to ビ (bi) with dakuten, ピ (pi) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "フ",
            romaji: "fu",
            type: .katakana,
            examples: ["フライパン (furaipan) - frying pan", "フォーク (fōku) - fork"],
            pronunciation: "like 'fu' with light 'h' sound",
            strokeOrder: "1. horizontal\n2. vertical sweep",
            notes: "Changes to ブ (bu) with dakuten, プ (pu) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ヘ",
            romaji: "he",
            type: .katakana,
            examples: ["ヘリコプター (herikoputā) - helicopter", "ページ (pēji) - page"],
            pronunciation: "like 'he' in 'help'",
            strokeOrder: "1. curved horizontal",
            notes: "Changes to ベ (be) with dakuten, ペ (pe) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ホ",
            romaji: "ho",
            type: .katakana,
            examples: ["ホテル (hoteru) - hotel", "ホーム (hōmu) - platform/home"],
            pronunciation: "like 'ho' in 'hope'",
            strokeOrder: "1. vertical\n2. horizontal\n3. vertical",
            notes: "Changes to ボ (bo) with dakuten, ポ (po) with handakuten",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        // M-row (マ行)
        Character(
            symbol: "マ",
            romaji: "ma",
            type: .katakana,
            examples: ["マウス (mausu) - mouse", "マンガ (manga) - manga/comic"],
            pronunciation: "like 'ma' in 'mama'",
            strokeOrder: "1. vertical\n2. diagonal\n3. diagonal",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ミ",
            romaji: "mi",
            type: .katakana,
            examples: ["ミルク (miruku) - milk", "ミュージック (myūjikku) - music"],
            pronunciation: "like 'me' in 'me'",
            strokeOrder: "1. short diagonal\n2. short diagonal\n3. short diagonal",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ム",
            romaji: "mu",
            type: .katakana,
            examples: ["ムービー (mūbī) - movie", "メニュー (menyū) - menu"],
            pronunciation: "like 'moo' in 'moon'",
            strokeOrder: "1. diagonal\n2. curved horizontal",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "メ",
            romaji: "me",
            type: .katakana,
            examples: ["メール (mēru) - email", "メモ (memo) - memo"],
            pronunciation: "like 'me' in 'met'",
            strokeOrder: "1. vertical\n2. diagonal cross",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "モ",
            romaji: "mo",
            type: .katakana,
            examples: ["モデル (moderu) - model", "モーター (mōtā) - motor"],
            pronunciation: "like 'mo' in 'more'",
            strokeOrder: "1. vertical\n2. horizontal\n3. diagonal",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // Y-row (ヤ行)
        Character(
            symbol: "ヤ",
            romaji: "ya",
            type: .katakana,
            examples: ["ヤクルト (yakuruto) - Yakult", "ヨーヤ (yōya) - lawyer"],
            pronunciation: "like 'ya' in 'yard'",
            strokeOrder: "1. diagonal\n2. vertical sweep",
            notes: "Also used as small ャ for combinations (キャ kya, シャ sha, etc.)",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ユ",
            romaji: "yu",
            type: .katakana,
            examples: ["ユーザー (yūzā) - user", "ユニフォーム (yunifōmu) - uniform"],
            pronunciation: "like 'yu' in 'you'",
            strokeOrder: "1. curve\n2. diagonal sweep",
            notes: "Also used as small ュ for combinations (キュ kyu, シュ shu, etc.)",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ヨ",
            romaji: "yo",
            type: .katakana,
            examples: ["ヨーグルト (yōguruto) - yogurt", "ヨット (yotto) - yacht"],
            pronunciation: "like 'yo' in 'yo-yo'",
            strokeOrder: "1. horizontal\n2. vertical\n3. horizontal",
            notes: "Also used as small ョ for combinations (キョ kyo, ショ sho, etc.)",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // R-row (ラ行) continued
        Character(
            symbol: "ラ",
            romaji: "ra",
            type: .katakana,
            examples: ["ラジオ (rajio) - radio", "ライト (raito) - light"],
            pronunciation: "like a mix of 'la' and 'ra'",
            strokeOrder: "1. diagonal\n2. curved angle",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "リ",
            romaji: "ri",
            type: .katakana,
            examples: ["リンク (rinku) - link", "リモコン (rimokon) - remote control"],
            pronunciation: "like a mix of 'li' and 'ri'",
            strokeOrder: "1. diagonal\n2. diagonal",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ル",
            romaji: "ru",
            type: .katakana,
            examples: ["ルーム (rūmu) - room", "ルール (rūru) - rule"],
            pronunciation: "like a mix of 'lu' and 'ru'",
            strokeOrder: "1. vertical curve\n2. hook",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "レ",
            romaji: "re",
            type: .katakana,
            examples: ["レストラン (resutoran) - restaurant", "レモン (remon) - lemon"],
            pronunciation: "like a mix of 'le' and 're'",
            strokeOrder: "1. diagonal\n2. diagonal",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ロ",
            romaji: "ro",
            type: .katakana,
            examples: ["ロボット (robotto) - robot", "ローマ (rōma) - Rome"],
            pronunciation: "like a mix of 'lo' and 'ro'",
            strokeOrder: "1. horizontal\n2. vertical\n3. horizontal\n4. vertical",
            notes: "No dakuten form. Looks like a square",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // W-row (ワ行)
        Character(
            symbol: "ワ",
            romaji: "wa",
            type: .katakana,
            examples: ["ワイン (wain) - wine", "ワット (watto) - watt"],
            pronunciation: "like 'wa' in 'water'",
            strokeOrder: "1. curved angle",
            notes: "No dakuten form",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "ヲ",
            romaji: "wo",
            type: .katakana,
            examples: ["rarely used except as particle を"],
            pronunciation: "like 'o' in 'go'",
            strokeOrder: "1. horizontal\n2. vertical sweep",
            notes: "Mostly used as particle を, pronounced 'o'",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // N (ン)
        Character(
            symbol: "ン",
            romaji: "n",
            type: .katakana,
            examples: ["パン (pan) - bread", "ペン (pen) - pen"],
            pronunciation: "like 'n' in 'sin'",
            strokeOrder: "1. curved diagonal",
            notes: "Be careful not to confuse with ソ (so). ン curves more at the bottom",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        
        // Special characters
        Character(
            symbol: "ー",
            romaji: "chōon",
            type: .katakana,
            examples: ["コーヒー (kōhī) - coffee", "スーパー (sūpā) - supermarket"],
            pronunciation: "extends the previous vowel sound",
            strokeOrder: "1. horizontal line",
            notes: "Used to indicate long vowels in katakana words",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "・",
            romaji: "nakaguro",
            type: .katakana,
            examples: ["ロック・バンド (rokku bando) - rock band"],
            pronunciation: "n/a",
            strokeOrder: "1. dot",
            notes: "Used as a separator in katakana words",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "゛",
            romaji: "dakuten",
            type: .katakana,
            examples: ["カ → ガ", "ハ → バ"],
            pronunciation: "n/a",
            strokeOrder: "1. two dots",
            notes: "Modifies consonant sound (k→g, s→z, t→d, h→b)",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        ),
        Character(
            symbol: "゜",
            romaji: "handakuten",
            type: .katakana,
            examples: ["ハ → パ", "ヒ → ピ"],
            pronunciation: "n/a",
            strokeOrder: "1. circle",
            notes: "Modifies h-row consonants to 'p' sounds",
            jlptLevel: nil,
            meaning: nil,
            onReading: nil,
            kunReading: nil
        )
        
    ]
    
    static let kanji: [Character] = [
        // Numbers and basic concepts
        Character(
            symbol: "一",
            romaji: "ichi/hitotsu",
            type: .kanji,
            examples: ["一日 (いちにち, ichinichi) - one day", "一番 (いちばん, ichiban) - number one"],
            pronunciation: "ichi (音), hitotsu (訓)",
            strokeOrder: "1. horizontal",
            notes: "Most basic kanji, represents horizontal line and the number one",
            jlptLevel: 5,
            meaning: "one",
            onReading: "イチ",
            kunReading: "ひと(つ)"
        ),
        Character(
            symbol: "二",
            romaji: "ni/futatsu",
            type: .kanji,
            examples: ["二月 (にがつ, nigatsu) - February", "二人 (ふたり, futari) - two people"],
            pronunciation: "ni (音), futatsu (訓)",
            strokeOrder: "1. top horizontal\n2. bottom horizontal",
            notes: "Represents two parallel lines",
            jlptLevel: 5,
            meaning: "two",
            onReading: "ニ",
            kunReading: "ふた(つ)"
        ),
        Character(
            symbol: "三",
            romaji: "san/mittsu",
            type: .kanji,
            examples: ["三日 (みっか, mikka) - third day", "三つ (みっつ, mittsu) - three things"],
            pronunciation: "san (音), mittsu (訓)",
            strokeOrder: "1. top horizontal\n2. middle horizontal\n3. bottom horizontal",
            notes: "Represents three parallel lines",
            jlptLevel: 5,
            meaning: "three",
            onReading: "サン",
            kunReading: "み(つ)"
        ),
        Character(
            symbol: "人",
            romaji: "jin/hito",
            type: .kanji,
            examples: ["日本人 (にほんじん, nihonjin) - Japanese person", "人々 (ひとびと, hitobito) - people"],
            pronunciation: "jin/nin (音), hito (訓)",
            strokeOrder: "1. left diagonal\n2. right diagonal",
            notes: "Represents a person walking",
            jlptLevel: 5,
            meaning: "person",
            onReading: "ジン、ニン",
            kunReading: "ひと"
        ),
        Character(
            symbol: "日",
            romaji: "nichi/hi",
            type: .kanji,
            examples: ["日本 (にほん, nihon) - Japan", "今日 (きょう, kyou) - today"],
            pronunciation: "nichi/jitsu (音), hi (訓)",
            strokeOrder: "1. horizontal\n2. vertical\n3. horizontal\n4. horizontal",
            notes: "Represents the sun",
            jlptLevel: 5,
            meaning: "day, sun",
            onReading: "ニチ、ジツ",
            kunReading: "ひ、-び、-か"
        ),
        Character(
            symbol: "月",
            romaji: "getsu/tsuki",
            type: .kanji,
            examples: ["月曜日 (げつようび, getsuyoubi) - Monday", "一月 (いちがつ, ichigatsu) - January"],
            pronunciation: "getsu/gatsu (音), tsuki (訓)",
            strokeOrder: "1. vertical\n2. horizontal\n3. vertical\n4. hook",
            notes: "Represents the moon",
            jlptLevel: 5,
            meaning: "month, moon",
            onReading: "ゲツ、ガツ",
            kunReading: "つき"
        ),
        Character(
            symbol: "年",
            romaji: "nen/toshi",
            type: .kanji,
            examples: ["今年 (ことし, kotoshi) - this year", "去年 (きょねん, kyonen) - last year"],
            pronunciation: "nen (音), toshi (訓)",
            strokeOrder: "1. horizontal\n2. vertical\n3. diagonal\n4. vertical\n5. horizontal\n6. vertical",
            notes: "Often used in time expressions",
            jlptLevel: 5,
            meaning: "year",
            onReading: "ネン",
            kunReading: "とし"
        ),
        Character(
            symbol: "上",
            romaji: "jou/ue",
            type: .kanji,
            examples: ["上手 (じょうず, jouzu) - skillful", "上がる (あがる, agaru) - to rise"],
            pronunciation: "jou (音), ue (訓)",
            strokeOrder: "1. horizontal\n2. vertical\n3. horizontal",
            notes: "Opposite of 下 (した, shita - down)",
            jlptLevel: 5,
            meaning: "up, above",
            onReading: "ジョウ",
            kunReading: "うえ、あ(がる)、のぼ(る)"
        ),
        Character(
            symbol: "下",
            romaji: "ka/shita",
            type: .kanji,
            examples: ["下手 (へた, heta) - unskillful", "下がる (さがる, sagaru) - to drop"],
            pronunciation: "ka/ge (音), shita (訓)",
            strokeOrder: "1. horizontal\n2. vertical\n3. horizontal",
            notes: "Opposite of 上 (うえ, ue - up)",
            jlptLevel: 5,
            meaning: "down, below",
            onReading: "カ、ゲ",
            kunReading: "した、さ(がる)、くだ(る)"
        ),
        Character(
            symbol: "中",
            romaji: "chuu/naka",
            type: .kanji,
            examples: ["中国 (ちゅうごく, chuugoku) - China", "中心 (ちゅうしん, chuushin) - center"],
            pronunciation: "chuu (音), naka (訓)",
            strokeOrder: "1. vertical\n2. vertical\n3. horizontal\n4. vertical",
            notes: "Represents something going through the middle",
            jlptLevel: 5,
            meaning: "middle, center",
            onReading: "チュウ",
            kunReading: "なか"
        ),
        // Basic elements and nature
        Character(
            symbol: "木",
            romaji: "ki/moku",
            type: .kanji,
            examples: ["木曜日 (もくようび, mokuyoubi) - Thursday", "木村 (きむら, kimura) - common surname"],
            pronunciation: "moku (音), ki (訓)",
            strokeOrder: "1. vertical\n2. horizontal\n3. left diagonal\n4. right diagonal",
            notes: "Pictograph of a tree, used as radical in many nature-related kanji",
            jlptLevel: 5,
            meaning: "tree, wood",
            onReading: "モク、ボク",
            kunReading: "き"
        ),
        Character(
            symbol: "火",
            romaji: "hi/ka",
            type: .kanji,
            examples: ["火曜日 (かようび, kayoubi) - Tuesday", "火事 (かじ, kaji) - fire incident"],
            pronunciation: "ka (音), hi (訓)",
            strokeOrder: "1. diagonal\n2. right stroke\n3. left stroke\n4. middle stroke",
            notes: "Pictograph of flames",
            jlptLevel: 5,
            meaning: "fire",
            onReading: "カ",
            kunReading: "ひ"
        ),
        Character(
            symbol: "水",
            romaji: "mizu/sui",
            type: .kanji,
            examples: ["水曜日 (すいようび, suiyoubi) - Wednesday", "水泳 (すいえい, suiei) - swimming"],
            pronunciation: "sui (音), mizu (訓)",
            strokeOrder: "1. left dot\n2. vertical\n3. left diagonal\n4. right diagonal",
            notes: "Represents flowing water",
            jlptLevel: 5,
            meaning: "water",
            onReading: "スイ",
            kunReading: "みず"
        ),
        Character(
            symbol: "金",
            romaji: "kin/kane",
            type: .kanji,
            examples: ["金曜日 (きんようび, kinyoubi) - Friday", "お金 (おかね, okane) - money"],
            pronunciation: "kin/kon (音), kane (訓)",
            strokeOrder: "1. top\n2. vertical\n3. left horizontal\n4. right horizontal\n5. bottom enclosure",
            notes: "Means both metal and money/gold",
            jlptLevel: 5,
            meaning: "gold, money, metal",
            onReading: "キン、コン",
            kunReading: "かね、かな-"
        ),
        Character(
            symbol: "土",
            romaji: "do/tsuchi",
            type: .kanji,
            examples: ["土曜日 (どようび, doyoubi) - Saturday", "土地 (とち, tochi) - land, plot"],
            pronunciation: "do (音), tsuchi (訓)",
            strokeOrder: "1. horizontal\n2. vertical\n3. bottom line",
            notes: "Represents earth/soil",
            jlptLevel: 5,
            meaning: "earth, soil",
            onReading: "ド、ト",
            kunReading: "つち"
        ),
        Character(
            symbol: "生",
            romaji: "sei/nama/ki",
            type: .kanji,
            examples: ["生徒 (せいと, seito) - student", "誕生日 (たんじょうび, tanjoubi) - birthday"],
            pronunciation: "sei/shou (音), i/ki/na (訓)",
            strokeOrder: "1. horizontal\n2. vertical\n3. diagonal\n4. horizontal\n5. sweep",
            notes: "Very versatile kanji with many meanings related to life/living",
            jlptLevel: 5,
            meaning: "life, birth, raw",
            onReading: "セイ、ショウ",
            kunReading: "い(きる)、う(まれる)、なま"
        ),
        Character(
            symbol: "先",
            romaji: "sen/saki",
            type: .kanji,
            examples: ["先生 (せんせい, sensei) - teacher", "先週 (せんしゅう, senshuu) - last week"],
            pronunciation: "sen (音), saki (訓)",
            strokeOrder: "1. dot\n2. horizontal\n3. vertical\n4. horizontal\n5. legs",
            notes: "Often used in time expressions for 'previous' or 'ahead'",
            jlptLevel: 5,
            meaning: "before, ahead, previous",
            onReading: "セン",
            kunReading: "さき"
        ),
        Character(
            symbol: "大",
            romaji: "dai/oo",
            type: .kanji,
            examples: ["大学 (だいがく, daigaku) - university", "大きい (おおきい, ookii) - big"],
            pronunciation: "dai/tai (音), oo (訓)",
            strokeOrder: "1. horizontal\n2. vertical\n3. diagonal",
            notes: "Represents a person with outstretched arms",
            jlptLevel: 5,
            meaning: "big, large",
            onReading: "ダイ、タイ",
            kunReading: "おお(きい)"
        ),
        Character(
            symbol: "小",
            romaji: "shou/chiisai",
            type: .kanji,
            examples: ["小学校 (しょうがっこう, shougakkou) - elementary school", "小さい (ちいさい, chiisai) - small"],
            pronunciation: "shou (音), chiisa/ko (訓)",
            strokeOrder: "1. vertical\n2. horizontal\n3. diagonal",
            notes: "Opposite of 大",
            jlptLevel: 5,
            meaning: "small",
            onReading: "ショウ",
            kunReading: "ちい(さい)、こ-"
        ),
        Character(
            symbol: "山",
            romaji: "san/yama",
            type: .kanji,
            examples: ["富士山 (ふじさん, fujisan) - Mt. Fuji", "山田 (やまだ, yamada) - common surname"],
            pronunciation: "san (音), yama (訓)",
            strokeOrder: "1. left diagonal\n2. right diagonal\n3. middle vertical",
            notes: "Pictograph of three mountain peaks",
            jlptLevel: 5,
            meaning: "mountain",
            onReading: "サン",
            kunReading: "やま"
        ),
        Character(
            symbol: "本",
            romaji: "hon/moto",
            type: .kanji,
            examples: ["日本 (にほん, nihon) - Japan", "本屋 (ほんや, honya) - bookstore"],
            pronunciation: "hon (音), moto (訓)",
            strokeOrder: "1. vertical\n2. horizontal\n3. bottom vertical",
            notes: "Originally meant 'root/origin', now commonly used in words related to books",
            jlptLevel: 5,
            meaning: "book, origin, real",
            onReading: "ホン",
            kunReading: "もと"
        ),
        Character(
            symbol: "田",
            romaji: "ta/den",
            type: .kanji,
            examples: ["田中 (たなか, tanaka) - common surname", "水田 (すいでん, suiden) - rice paddy"],
            pronunciation: "den (音), ta (訓)",
            strokeOrder: "1. outer square\n2. vertical line\n3. horizontal line",
            notes: "Represents a rice field, very common in surnames",
            jlptLevel: 5,
            meaning: "rice field",
            onReading: "デン",
            kunReading: "た"
        ),
        Character(
            symbol: "時",
            romaji: "ji/toki",
            type: .kanji,
            examples: ["時間 (じかん, jikan) - time", "時計 (とけい, tokei) - clock/watch"],
            pronunciation: "ji (音), toki (訓)",
            strokeOrder: "1. sun radical\n2. temple radical",
            notes: "Essential for time-related expressions",
            jlptLevel: 5,
            meaning: "time, hour",
            onReading: "ジ",
            kunReading: "とき"
        ),
        Character(
            symbol: "分",
            romaji: "fun/bun/wa",
            type: .kanji,
            examples: ["一分 (いっぷん, ippun) - one minute", "自分 (じぶん, jibun) - oneself"],
            pronunciation: "fun/bun (音), wa (訓)",
            strokeOrder: "1. left cut\n2. right eight",
            notes: "Used for minutes and division/understanding",
            jlptLevel: 5,
            meaning: "minute, to divide, understand",
            onReading: "フン、ブン",
            kunReading: "わ(かる)"
        ),
        Character(
            symbol: "立",
            romaji: "ritsu/ta",
            type: .kanji,
            examples: ["立つ (たつ, tatsu) - to stand", "設立 (せつりつ, setsuritsu) - establishment"],
            pronunciation: "ritsu (音), ta (訓)",
            strokeOrder: "1. vertical\n2. horizontal\n3. bottom legs",
            notes: "Represents a person standing",
            jlptLevel: 5,
            meaning: "stand, establish",
            onReading: "リツ、リュウ",
            kunReading: "た(つ)"
        ),
        Character(
            symbol: "見",
            romaji: "ken/mi",
            type: .kanji,
            examples: ["見る (みる, miru) - to see", "意見 (いけん, iken) - opinion"],
            pronunciation: "ken (音), mi (訓)",
            strokeOrder: "1. top horizontal\n2. eye radical\n3. legs",
            notes: "Represents an eye with legs",
            jlptLevel: 5,
            meaning: "see, look",
            onReading: "ケン",
            kunReading: "み(る)"
        ),
        Character(
            symbol: "行",
            romaji: "kou/i/yu",
            type: .kanji,
            examples: ["行く (いく, iku) - to go", "銀行 (ぎんこう, ginkou) - bank"],
            pronunciation: "kou/gyou (音), i/yu (訓)",
            strokeOrder: "1. vertical\n2. horizontal\n3. vertical sweep",
            notes: "Very common in words related to movement or institutions",
            jlptLevel: 5,
            meaning: "go, travel, do",
            onReading: "コウ、ギョウ",
            kunReading: "い(く)、おこな(う)"
        ),
        Character(
            symbol: "食",
            romaji: "shoku/ta",
            type: .kanji,
            examples: ["食べる (たべる, taberu) - to eat", "食堂 (しょくどう, shokudou) - dining hall"],
            pronunciation: "shoku (音), ta (訓)",
            strokeOrder: "1. top box\n2. good radical",
            notes: "Essential for words related to food and eating",
            jlptLevel: 5,
            meaning: "eat, food",
            onReading: "ショク",
            kunReading: "た(べる)"
        ),
        Character(
            symbol: "間",
            romaji: "kan/aida",
            type: .kanji,
            examples: ["時間 (じかん, jikan) - time", "中間 (ちゅうかん, chuukan) - middle/interim"],
            pronunciation: "kan/ken (音), aida (訓)",
            strokeOrder: "1. gate radical\n2. sun radical",
            notes: "Used in many time and space-related expressions",
            jlptLevel: 5,
            meaning: "interval, between",
            onReading: "カン、ケン",
            kunReading: "あいだ"
        ),
        Character(
            symbol: "出",
            romaji: "shutsu/de",
            type: .kanji,
            examples: ["出る (でる, deru) - to exit", "出発 (しゅっぱつ, shuppatsu) - departure"],
            pronunciation: "shutsu (音), de (訓)",
            strokeOrder: "1. horizontal\n2. vertical\n3. mountain",
            notes: "Represents something coming out of a container",
            jlptLevel: 5,
            meaning: "exit, leave",
            onReading: "シュツ",
            kunReading: "で(る)、だ(す)"
        ),
        Character(
            symbol: "本",
            romaji: "hon/moto",
            type: .kanji,
            examples: ["日本 (にほん, nihon) - Japan", "本屋 (ほんや, honya) - bookstore"],
            pronunciation: "hon (音), moto (訓)",
            strokeOrder: "1. vertical\n2. horizontal\n3. bottom vertical",
            notes: "Originally meant 'root/origin', now commonly used in words related to books",
            jlptLevel: 5,
            meaning: "book, origin, real",
            onReading: "ホン",
            kunReading: "もと"
        ),
        Character(
            symbol: "田",
            romaji: "ta/den",
            type: .kanji,
            examples: ["田中 (たなか, tanaka) - common surname", "水田 (すいでん, suiden) - rice paddy"],
            pronunciation: "den (音), ta (訓)",
            strokeOrder: "1. outer square\n2. vertical line\n3. horizontal line",
            notes: "Represents a rice field, very common in surnames",
            jlptLevel: 5,
            meaning: "rice field",
            onReading: "デン",
            kunReading: "た"
        ),
        Character(
            symbol: "時",
            romaji: "ji/toki",
            type: .kanji,
            examples: ["時間 (じかん, jikan) - time", "時計 (とけい, tokei) - clock/watch"],
            pronunciation: "ji (音), toki (訓)",
            strokeOrder: "1. sun radical\n2. temple radical",
            notes: "Essential for time-related expressions",
            jlptLevel: 5,
            meaning: "time, hour",
            onReading: "ジ",
            kunReading: "とき"
        ),
        Character(
            symbol: "分",
            romaji: "fun/bun/wa",
            type: .kanji,
            examples: ["一分 (いっぷん, ippun) - one minute", "自分 (じぶん, jibun) - oneself"],
            pronunciation: "fun/bun (音), wa (訓)",
            strokeOrder: "1. left cut\n2. right eight",
            notes: "Used for minutes and division/understanding",
            jlptLevel: 5,
            meaning: "minute, to divide, understand",
            onReading: "フン、ブン",
            kunReading: "わ(かる)"
        ),
        Character(
            symbol: "立",
            romaji: "ritsu/ta",
            type: .kanji,
            examples: ["立つ (たつ, tatsu) - to stand", "設立 (せつりつ, setsuritsu) - establishment"],
            pronunciation: "ritsu (音), ta (訓)",
            strokeOrder: "1. vertical\n2. horizontal\n3. bottom legs",
            notes: "Represents a person standing",
            jlptLevel: 5,
            meaning: "stand, establish",
            onReading: "リツ、リュウ",
            kunReading: "た(つ)"
        ),
        Character(
            symbol: "見",
            romaji: "ken/mi",
            type: .kanji,
            examples: ["見る (みる, miru) - to see", "意見 (いけん, iken) - opinion"],
            pronunciation: "ken (音), mi (訓)",
            strokeOrder: "1. top horizontal\n2. eye radical\n3. legs",
            notes: "Represents an eye with legs",
            jlptLevel: 5,
            meaning: "see, look",
            onReading: "ケン",
            kunReading: "み(る)"
        ),
        Character(
            symbol: "行",
            romaji: "kou/i/yu",
            type: .kanji,
            examples: ["行く (いく, iku) - to go", "銀行 (ぎんこう, ginkou) - bank"],
            pronunciation: "kou/gyou (音), i/yu (訓)",
            strokeOrder: "1. vertical\n2. horizontal\n3. vertical sweep",
            notes: "Very common in words related to movement or institutions",
            jlptLevel: 5,
            meaning: "go, travel, do",
            onReading: "コウ、ギョウ",
            kunReading: "い(く)、おこな(う)"
        ),
        Character(
            symbol: "食",
            romaji: "shoku/ta",
            type: .kanji,
            examples: ["食べる (たべる, taberu) - to eat", "食堂 (しょくどう, shokudou) - dining hall"],
            pronunciation: "shoku (音), ta (訓)",
            strokeOrder: "1. top box\n2. good radical",
            notes: "Essential for words related to food and eating",
            jlptLevel: 5,
            meaning: "eat, food",
            onReading: "ショク",
            kunReading: "た(べる)"
        ),
        Character(
            symbol: "間",
            romaji: "kan/aida",
            type: .kanji,
            examples: ["時間 (じかん, jikan) - time", "中間 (ちゅうかん, chuukan) - middle/interim"],
            pronunciation: "kan/ken (音), aida (訓)",
            strokeOrder: "1. gate radical\n2. sun radical",
            notes: "Used in many time and space-related expressions",
            jlptLevel: 5,
            meaning: "interval, between",
            onReading: "カン、ケン",
            kunReading: "あいだ"
        ),
        Character(
            symbol: "出",
            romaji: "shutsu/de",
            type: .kanji,
            examples: ["出る (でる, deru) - to exit", "出発 (しゅっぱつ, shuppatsu) - departure"],
            pronunciation: "shutsu (音), de (訓)",
            strokeOrder: "1. horizontal\n2. vertical\n3. mountain",
            notes: "Represents something coming out of a container",
            jlptLevel: 5,
            meaning: "exit, leave",
            onReading: "シュツ",
            kunReading: "で(る)、だ(す)"
        ),
        Character(
            symbol: "耳",
            romaji: "mimi/ji",
            type: .kanji,
            examples: ["耳 (みみ, mimi) - ear", "右耳 (みぎみみ, migimimi) - right ear"],
            pronunciation: "ji (音), mimi (訓)",
            strokeOrder: "1. top\n2. middle horizontal\n3. bottom hooks",
            notes: "Pictograph of an ear",
            jlptLevel: 5,
            meaning: "ear",
            onReading: "ジ",
            kunReading: "みみ"
        ),
        Character(
            symbol: "休",
            romaji: "kyuu/yasu",
            type: .kanji,
            examples: ["休む (やすむ, yasumu) - to rest", "休日 (きゅうじつ, kyuujitsu) - holiday"],
            pronunciation: "kyuu (音), yasu (訓)",
            strokeOrder: "1. person radical\n2. tree radical",
            notes: "Shows person leaning against tree - resting",
            jlptLevel: 5,
            meaning: "rest, holiday",
            onReading: "キュウ",
            kunReading: "やす(む)"
        ),
        Character(
            symbol: "体",
            romaji: "karada/tai",
            type: .kanji,
            examples: ["体 (からだ, karada) - body", "団体 (だんたい, dantai) - organization"],
            pronunciation: "tai (音), karada (訓)",
            strokeOrder: "1. person radical\n2. book radical",
            notes: "Used for physical body and abstract bodies/organizations",
            jlptLevel: 5,
            meaning: "body",
            onReading: "タイ、テイ",
            kunReading: "からだ"
        ),
        Character(
            symbol: "男",
            romaji: "otoko/dan",
            type: .kanji,
            examples: ["男の人 (おとこのひと, otokonohito) - man", "男性 (だんせい, dansei) - male"],
            pronunciation: "dan/nan (音), otoko (訓)",
            strokeOrder: "1. field radical\n2. power radical",
            notes: "Combines field (田) and power (力)",
            jlptLevel: 5,
            meaning: "man, male",
            onReading: "ダン、ナン",
            kunReading: "おとこ"
        ),
        Character(
            symbol: "女",
            romaji: "onna/jo",
            type: .kanji,
            examples: ["女の人 (おんなのひと, onnanohito) - woman", "女性 (じょせい, josei) - female"],
            pronunciation: "jo/nyo (音), onna (訓)",
            strokeOrder: "1. left curve\n2. middle curve\n3. right leg",
            notes: "Pictograph of a woman kneeling",
            jlptLevel: 5,
            meaning: "woman, female",
            onReading: "ジョ、ニョ",
            kunReading: "おんな"
        ),
        Character(
            symbol: "子",
            romaji: "ko/shi",
            type: .kanji,
            examples: ["子供 (こども, kodomo) - child", "女子 (じょし, joshi) - girl"],
            pronunciation: "shi/su (音), ko (訓)",
            strokeOrder: "1. top horizontal\n2. wrap\n3. legs",
            notes: "Represents a child wrapped in cloth",
            jlptLevel: 5,
            meaning: "child",
            onReading: "シ、ス",
            kunReading: "こ"
        ),
        Character(
            symbol: "父",
            romaji: "chichi/fu",
            type: .kanji,
            examples: ["父 (ちち, chichi) - father", "父親 (ちちおや, chichioya) - father"],
            pronunciation: "fu (音), chichi (訓)",
            strokeOrder: "1. left stroke\n2. right strokes",
            notes: "Basic family kanji",
            jlptLevel: 5,
            meaning: "father",
            onReading: "フ",
            kunReading: "ちち"
        ),
        Character(
            symbol: "母",
            romaji: "haha/bo",
            type: .kanji,
            examples: ["母 (はは, haha) - mother", "母親 (ははおや, hahaoya) - mother"],
            pronunciation: "bo (音), haha (訓)",
            strokeOrder: "1. dots\n2. vertical\n3. wrap",
            notes: "Basic family kanji",
            jlptLevel: 5,
            meaning: "mother",
            onReading: "ボ",
            kunReading: "はは"
        ),
        Character(
            symbol: "東",
            romaji: "higashi/tou",
            type: .kanji,
            examples: ["東京 (とうきょう, toukyou) - Tokyo", "東 (ひがし, higashi) - east"],
            pronunciation: "tou (音), higashi (訓)",
            strokeOrder: "1. tree radical\n2. sun through trees",
            notes: "Shows sun rising through trees",
            jlptLevel: 5,
            meaning: "east",
            onReading: "トウ",
            kunReading: "ひがし"
        ),
        Character(
            symbol: "西",
            romaji: "nishi/sei",
            type: .kanji,
            examples: ["西 (にし, nishi) - west", "関西 (かんさい, kansai) - Kansai region"],
            pronunciation: "sei/sai (音), nishi (訓)",
            strokeOrder: "1. container\n2. dividing line",
            notes: "Originally depicted a bird in its nest",
            jlptLevel: 5,
            meaning: "west",
            onReading: "セイ、サイ",
            kunReading: "にし"
        ),
        Character(
            symbol: "南",
            romaji: "minami/nan",
            type: .kanji,
            examples: ["南 (みなみ, minami) - south", "南口 (みなみぐち, minamiguchi) - south entrance"],
            pronunciation: "nan (音), minami (訓)",
            strokeOrder: "1. top\n2. box\n3. vertical\n4. cross",
            notes: "One of the four cardinal directions",
            jlptLevel: 5,
            meaning: "south",
            onReading: "ナン、ナ",
            kunReading: "みなみ"
        ),
        Character(
            symbol: "北",
            romaji: "kita/hoku",
            type: .kanji,
            examples: ["北 (きた, kita) - north", "北海道 (ほっかいどう, hokkaidou) - Hokkaido"],
            pronunciation: "hoku (音), kita (訓)",
            strokeOrder: "1. left stroke\n2. right stroke\n3. bottom",
            notes: "Opposite of 南 (south)",
            jlptLevel: 5,
            meaning: "north",
            onReading: "ホク",
            kunReading: "きた"
        ),
        Character(
            symbol: "右",
            romaji: "migi/u",
            type: .kanji,
            examples: ["右 (みぎ, migi) - right", "右手 (みぎて, migite) - right hand"],
            pronunciation: "u/yuu (音), migi (訓)",
            strokeOrder: "1. mouth radical\n2. hand radical",
            notes: "Remember: right is 'correct' in many cultures",
            jlptLevel: 5,
            meaning: "right",
            onReading: "ウ、ユウ",
            kunReading: "みぎ"
        ),
        Character(
            symbol: "左",
            romaji: "hidari/sa",
            type: .kanji,
            examples: ["左 (ひだり, hidari) - left", "左手 (ひだりて, hidarite) - left hand"],
            pronunciation: "sa (音), hidari (訓)",
            strokeOrder: "1. work radical\n2. hand radical",
            notes: "Opposite of 右 (right)",
            jlptLevel: 5,
            meaning: "left",
            onReading: "サ",
            kunReading: "ひだり"
        ),
        Character(
            symbol: "外",
            romaji: "soto/gai",
            type: .kanji,
            examples: ["外国 (がいこく, gaikoku) - foreign country", "外 (そと, soto) - outside"],
            pronunciation: "gai/ge (音), soto (訓)",
            strokeOrder: "1. top\n2. evening radical\n3. legs",
            notes: "Contrasts with 中 (inside/middle)",
            jlptLevel: 5,
            meaning: "outside, foreign",
            onReading: "ガイ、ゲ",
            kunReading: "そと"
        ),
        Character(
            symbol: "内",
            romaji: "uchi/nai",
            type: .kanji,
            examples: ["内 (うち, uchi) - inside/home", "案内 (あんない, annai) - guidance"],
            pronunciation: "nai/dai (音), uchi (訓)",
            strokeOrder: "1. vertical\n2. inner stroke",
            notes: "Opposite of 外 (outside)",
            jlptLevel: 5,
            meaning: "inside, within",
            onReading: "ナイ、ダイ",
            kunReading: "うち"
        ),
        Character(
            symbol: "前",
            romaji: "mae/zen",
            type: .kanji,
            examples: ["前 (まえ, mae) - front/before", "名前 (なまえ, namae) - name"],
            pronunciation: "zen (音), mae (訓)",
            strokeOrder: "1. top\n2. moon\n3. legs",
            notes: "Used in both spatial and temporal contexts",
            jlptLevel: 5,
            meaning: "before, front",
            onReading: "ゼン",
            kunReading: "まえ"
        ),
        Character(
            symbol: "後",
            romaji: "ato/go",
            type: .kanji,
            examples: ["後ろ (うしろ, ushiro) - behind", "午後 (ごご, gogo) - afternoon"],
            pronunciation: "go/kou (音), ato (訓)",
            strokeOrder: "1. walk radical\n2. modified day radical",
            notes: "Opposite of 前 (before/front)",
            jlptLevel: 5,
            meaning: "after, behind",
            onReading: "ゴ、コウ",
            kunReading: "あと、うし(ろ)"
        ),
        Character(
            symbol: "午",
            romaji: "go",
            type: .kanji,
            examples: ["午前 (ごぜん, gozen) - morning/AM", "正午 (しょうご, shougo) - noon"],
            pronunciation: "go (音)",
            strokeOrder: "1. top stroke\n2. bottom cross",
            notes: "Used primarily in time expressions",
            jlptLevel: 5,
            meaning: "noon, sign of the horse",
            onReading: "ゴ",
            kunReading: ""
        ),
        Character(
            symbol: "門",
            romaji: "mon/kado",
            type: .kanji,
            examples: ["門 (もん, mon) - gate", "専門 (せんもん, senmon) - specialty"],
            pronunciation: "mon (音), kado (訓)",
            strokeOrder: "1. left side\n2. right side\n3. top\n4. bottom",
            notes: "Pictograph of a gate",
            jlptLevel: 5,
            meaning: "gate, door",
            onReading: "モン",
            kunReading: "かど"
        ),
        Character(
            symbol: "聞",
            romaji: "kiku/bun",
            type: .kanji,
            examples: ["聞く (きく, kiku) - to hear/listen", "新聞 (しんぶん, shinbun) - newspaper"],
            pronunciation: "bun/mon (音), kiku (訓)",
            strokeOrder: "1. ear radical\n2. gate radical",
            notes: "Combines ear (耳) and gate (門) - hearing through a gate",
            jlptLevel: 5,
            meaning: "hear, ask, listen",
            onReading: "ブン、モン",
            kunReading: "き(く)"
        ),
        Character(
            symbol: "読",
            romaji: "yomu/doku",
            type: .kanji,
            examples: ["読む (よむ, yomu) - to read", "読書 (どくしょ, dokusho) - reading"],
            pronunciation: "doku (音), yo (訓)",
            strokeOrder: "1. speech radical\n2. sell radical",
            notes: "Essential verb for studying",
            jlptLevel: 5,
            meaning: "read",
            onReading: "ドク",
            kunReading: "よ(む)"
        ),
        Character(
            symbol: "話",
            romaji: "hanashi/wa",
            type: .kanji,
            examples: ["話す (はなす, hanasu) - to speak", "電話 (でんわ, denwa) - telephone"],
            pronunciation: "wa (音), hanashi (訓)",
            strokeOrder: "1. speech radical\n2. tongue radical",
            notes: "Essential for communication-related words",
            jlptLevel: 5,
            meaning: "speak, talk",
            onReading: "ワ",
            kunReading: "はな(す)、はなし"
        ),
        Character(
            symbol: "書",
            romaji: "kaku/sho",
            type: .kanji,
            examples: ["書く (かく, kaku) - to write", "辞書 (じしょ, jisho) - dictionary"],
            pronunciation: "sho (音), ka (訓)",
            strokeOrder: "1. top radical\n2. brush strokes",
            notes: "Shows a hand holding a writing brush",
            jlptLevel: 5,
            meaning: "write",
            onReading: "ショ",
            kunReading: "か(く)"
        ),
        Character(
            symbol: "友",
            romaji: "tomo/yuu",
            type: .kanji,
            examples: ["友達 (ともだち, tomodachi) - friend", "友人 (ゆうじん, yuujin) - friend"],
            pronunciation: "yuu (音), tomo (訓)",
            strokeOrder: "1. left hand\n2. right hand",
            notes: "Shows two hands joining - friendship",
            jlptLevel: 5,
            meaning: "friend",
            onReading: "ユウ",
            kunReading: "とも"
        ),
        Character(
            symbol: "語",
            romaji: "go/kata",
            type: .kanji,
            examples: ["日本語 (にほんご, nihongo) - Japanese language", "英語 (えいご, eigo) - English"],
            pronunciation: "go (音)",
            strokeOrder: "1. speech radical\n2. word radical\n3. five radical",
            notes: "Essential for language names",
            jlptLevel: 5,
            meaning: "language, word",
            onReading: "ゴ",
            kunReading: "かた(る)"
        ),
        Character(
            symbol: "校",
            romaji: "kou",
            type: .kanji,
            examples: ["学校 (がっこう, gakkou) - school", "高校 (こうこう, koukou) - high school"],
            pronunciation: "kou (音)",
            strokeOrder: "1. tree radical\n2. crossing radical",
            notes: "Almost exclusively used for school-related words",
            jlptLevel: 5,
            meaning: "school",
            onReading: "コウ",
            kunReading: ""
        ),
        Character(
            symbol: "会",
            romaji: "kai/a",
            type: .kanji,
            examples: ["会社 (かいしゃ, kaisha) - company", "会う (あう, au) - to meet"],
            pronunciation: "kai/e (音), a (訓)",
            strokeOrder: "1. top cover\n2. person radical",
            notes: "Used for meetings and organizations",
            jlptLevel: 5,
            meaning: "meet, society",
            onReading: "カイ、エ",
            kunReading: "あ(う)"
        ),
        Character(
            symbol: "社",
            romaji: "sha/yashiro",
            type: .kanji,
            examples: ["会社 (かいしゃ, kaisha) - company", "神社 (じんじゃ, jinja) - shrine"],
            pronunciation: "sha (音), yashiro (訓)",
            strokeOrder: "1. shelter radical\n2. earth radical",
            notes: "Used for companies and shrines",
            jlptLevel: 5,
            meaning: "company, shrine",
            onReading: "シャ",
            kunReading: "やしろ"
        ),
        Character(
            symbol: "高",
            romaji: "taka/kou",
            type: .kanji,
            examples: ["高い (たかい, takai) - expensive/tall", "高校 (こうこう, koukou) - high school"],
            pronunciation: "kou (音), taka (訓)",
            strokeOrder: "1. top layer\n2. middle layer\n3. bottom mouth",
            notes: "Used for height, price, and status",
            jlptLevel: 5,
            meaning: "high, expensive",
            onReading: "コウ",
            kunReading: "たか(い)、たか"
        ),
        Character(
            symbol: "新",
            romaji: "shin/atara",
            type: .kanji,
            examples: ["新しい (あたらしい, atarashii) - new", "新聞 (しんぶん, shinbun) - newspaper"],
            pronunciation: "shin (音), atara (訓)",
            strokeOrder: "1. tree\n2. axe\n3. stand",
            notes: "Combines 立 (stand) with other elements to mean 'newly standing'",
            jlptLevel: 5,
            meaning: "new",
            onReading: "シン",
            kunReading: "あたら(しい)、あら(た)"
        ),
        Character(
            symbol: "古",
            romaji: "furu/ko",
            type: .kanji,
            examples: ["古い (ふるい, furui) - old", "中古 (ちゅうこ, chuuko) - used/second-hand"],
            pronunciation: "ko (音), furu (訓)",
            strokeOrder: "1. top cross\n2. bottom box",
            notes: "Opposite of 新 (new)",
            jlptLevel: 5,
            meaning: "old",
            onReading: "コ",
            kunReading: "ふる(い)、ふる"
        ),
        Character(
            symbol: "台",
            romaji: "dai/tai",
            type: .kanji,
            examples: ["台所 (だいどころ, daidokoro) - kitchen", "台風 (たいふう, taifuu) - typhoon"],
            pronunciation: "dai/tai (音)",
            strokeOrder: "1. top mouth\n2. stand",
            notes: "Used for platforms, stands, and counting machines",
            jlptLevel: 5,
            meaning: "platform, stand",
            onReading: "ダイ、タイ",
            kunReading: ""
        ),
        Character(
            symbol: "店",
            romaji: "mise/ten",
            type: .kanji,
            examples: ["店 (みせ, mise) - shop", "本店 (ほんてん, honten) - main store"],
            pronunciation: "ten (音), mise (訓)",
            strokeOrder: "1. roof\n2. mouth radical\n3. legs",
            notes: "Used for all types of shops and stores",
            jlptLevel: 5,
            meaning: "shop, store",
            onReading: "テン",
            kunReading: "みせ"
        ),
        Character(
            symbol: "買",
            romaji: "ka",
            type: .kanji,
            examples: ["買う (かう, kau) - to buy", "買い物 (かいもの, kaimono) - shopping"],
            pronunciation: "bai (音), ka (訓)",
            strokeOrder: "1. top net\n2. shell radical",
            notes: "Essential shopping/commerce kanji",
            jlptLevel: 5,
            meaning: "buy",
            onReading: "バイ",
            kunReading: "か(う)"
        ),
        Character(
            symbol: "売",
            romaji: "u/bai",
            type: .kanji,
            examples: ["売る (うる, uru) - to sell", "販売 (はんばい, hanbai) - sales"],
            pronunciation: "bai (音), u (訓)",
            strokeOrder: "1. top hat\n2. legs\n3. bottom",
            notes: "Opposite of 買 (buy)",
            jlptLevel: 5,
            meaning: "sell",
            onReading: "バイ",
            kunReading: "う(る)"
        ),
        Character(
            symbol: "午",
            romaji: "go",
            type: .kanji,
            examples: ["午前 (ごぜん, gozen) - morning", "正午 (しょうご, shougo) - noon"],
            pronunciation: "go (音)",
            strokeOrder: "1. top cross\n2. bottom cross",
            notes: "Used primarily in time expressions",
            jlptLevel: 5,
            meaning: "noon",
            onReading: "ゴ",
            kunReading: ""
        ),
        Character(
            symbol: "牛",
            romaji: "ushi/gyuu",
            type: .kanji,
            examples: ["牛肉 (ぎゅうにく, gyuuniku) - beef", "牛 (うし, ushi) - cow"],
            pronunciation: "gyuu (音), ushi (訓)",
            strokeOrder: "1. top horn\n2. head\n3. legs",
            notes: "Pictograph of a cow's head",
            jlptLevel: 5,
            meaning: "cow",
            onReading: "ギュウ",
            kunReading: "うし"
        ),
        Character(
            symbol: "魚",
            romaji: "sakana/gyo",
            type: .kanji,
            examples: ["魚 (さかな, sakana) - fish", "金魚 (きんぎょ, kingyo) - goldfish"],
            pronunciation: "gyo (音), sakana (訓)",
            strokeOrder: "1. top\n2. middle dots\n3. bottom tail",
            notes: "Pictograph of a fish",
            jlptLevel: 5,
            meaning: "fish",
            onReading: "ギョ",
            kunReading: "さかな"
        ),
        Character(
            symbol: "肉",
            romaji: "niku",
            type: .kanji,
            examples: ["肉 (にく, niku) - meat", "牛肉 (ぎゅうにく, gyuuniku) - beef"],
            pronunciation: "niku (音)",
            strokeOrder: "1. top\n2. inside\n3. bottom",
            notes: "Used for all types of meat",
            jlptLevel: 5,
            meaning: "meat",
            onReading: "ニク",
            kunReading: ""
        )
    ]
    
    static func getCharacterSet(_ type: Character.CharacterType) -> [Character] {
        switch type {
        case .hiragana:
            return hiragana
        case .katakana:
            return katakana
        case .kanji:
            return kanji
        }
    }
}
