//
//  VocabularySets.swift
//  Tateru
//
//  Created by Tiago Carvalho on 1/23/25.
//


enum VocabularySets {
    static let vocabulary = [
       Vocabulary(
           meaning: "Good morning (casual)",
           romaji: "ohayou",
           hiragana: "おはよう",
           katakana: "オハヨウ",
           kanji: "お早う",
           word: "おはよう",
           partOfSpeech: "Expression",
           category: .greetings,
           level: 5,
           examples: ["おはよう、元気?"],
           notes: "おはようございます for formal"
       ),
       Vocabulary(
           meaning: "Good morning (formal)",
           romaji: "ohayou gozaimasu",
           hiragana: "おはようございます",
           katakana: "オハヨウゴザイマス",
           kanji: "お早うございます",
           word: "おはようございます",
           partOfSpeech: "Expression",
           category: .greetings,
           level: 5,
           examples: ["おはようございます、先生。"],
           notes: nil
       ),
       Vocabulary(
           meaning: "Hello/Good afternoon",
           romaji: "konnichiwa",
           hiragana: "こんにちは",
           katakana: "コンニチハ",
           kanji: "今日は",
           word: "こんにちは",
           partOfSpeech: "Expression",
           category: .greetings,
           level: 5,
           examples: ["こんにちは、田中さん。"],
           notes: nil
       ),
       Vocabulary(
           meaning: "Good evening",
           romaji: "konbanwa",
           hiragana: "こんばんは",
           katakana: "コンバンハ",
           kanji: "今晩は",
           word: "こんばんは",
           partOfSpeech: "Expression",
           category: .greetings,
           level: 5,
           examples: ["こんばんは、お元気ですか。"],
           notes: nil
       ),
       Vocabulary(
           meaning: "Good night (casual)",
           romaji: "oyasumi",
           hiragana: "おやすみ",
           katakana: "オヤスミ",
           kanji: "お休み",
           word: "おやすみ",
           partOfSpeech: "Expression",
           category: .greetings,
           level: 5,
           examples: ["おやすみ、また明日。"],
           notes: "おやすみなさい for formal"
       ),
       Vocabulary(
           meaning: "Good night (formal)",
           romaji: "oyasuminasai",
           hiragana: "おやすみなさい",
           katakana: "オヤスミナサイ",
           kanji: "お休みなさい",
           word: "おやすみなさい",
           partOfSpeech: "Expression",
           category: .greetings,
           level: 5,
           examples: ["おやすみなさい、お母さん。"],
           notes: nil
       ),
       Vocabulary(
           meaning: "Welcome",
           romaji: "youkoso",
           hiragana: "ようこそ",
           katakana: "ヨウコソ",
           kanji: "様子",
           word: "ようこそ",
           partOfSpeech: "Expression",
           category: .greetings,
           level: 5,
           examples: ["ようこそ、日本へ。"],
           notes: nil
       ),
       Vocabulary(
           meaning: "Thank you",
           romaji: "arigatou",
           hiragana: "ありがとう",
           katakana: "アリガトウ",
           kanji: "有難う",
           word: "ありがとう",
           partOfSpeech: "Expression",
           category: .greetings,
           level: 5,
           examples: ["ありがとう、助かった。"],
           notes: "ありがとうございます for formal"
       ),
       Vocabulary(
           meaning: "See you later",
           romaji: "jaa ne",
           hiragana: "じゃあね",
           katakana: "ジャアネ",
           kanji: nil,
           word: "じゃあね",
           partOfSpeech: "Expression",
           category: .greetings,
           level: 5,
           examples: ["じゃあね、また明日。"],
           notes: "Casual farewell"
       ),
       Vocabulary(
           meaning: "Goodbye (formal)",
           romaji: "sayounara",
           hiragana: "さようなら",
           katakana: "サヨウナラ",
           kanji: "左様なら",
           word: "さようなら",
           partOfSpeech: "Expression",
           category: .greetings,
           level: 5,
           examples: ["さようなら、お気をつけて。"],
           notes: "Used for long-term goodbyes"
       ),
       // Days of the week
       Vocabulary(
           meaning: "Sunday",
           romaji: "nichiyoubi",
           hiragana: "にちようび",
           katakana: "ニチヨウビ",
           kanji: "日曜日",
           word: "日曜日",
           partOfSpeech: "Noun",
           category: .calendar,
           level: 5,
           examples: ["日曜日は休みです。"],
           notes: nil
       ),
       Vocabulary(
           meaning: "Monday",
           romaji: "getsuyoubi",
           hiragana: "げつようび",
           katakana: "ゲツヨウビ",
           kanji: "月曜日",
           word: "月曜日",
           partOfSpeech: "Noun",
           category: .calendar,
           level: 5,
           examples: ["月曜日から仕事です。"],
           notes: nil
       ),
       Vocabulary(
           meaning: "Tuesday",
           romaji: "kayoubi",
           hiragana: "かようび",
           katakana: "カヨウビ",
           kanji: "火曜日",
           word: "火曜日",
           partOfSpeech: "Noun",
           category: .calendar,
           level: 5,
           examples: ["火曜日に会議があります。"],
           notes: nil
       ),
       Vocabulary(
           meaning: "Wednesday",
           romaji: "suiyoubi",
           hiragana: "すいようび",
           katakana: "スイヨウビ",
           kanji: "水曜日",
           word: "水曜日",
           partOfSpeech: "Noun",
           category: .calendar,
           level: 5,
           examples: ["水曜日は早く終わります。"],
           notes: nil
       ),
       Vocabulary(
           meaning: "Thursday",
           romaji: "mokuyoubi",
           hiragana: "もくようび",
           katakana: "モクヨウビ",
           kanji: "木曜日",
           word: "木曜日",
           partOfSpeech: "Noun",
           category: .calendar,
           level: 5,
           examples: ["木曜日に友達と会います。"],
           notes: nil
       ),
       Vocabulary(
           meaning: "Friday",
           romaji: "kinyoubi",
           hiragana: "きんようび",
           katakana: "キンヨウビ",
           kanji: "金曜日",
           word: "金曜日",
           partOfSpeech: "Noun",
           category: .calendar,
           level: 5,
           examples: ["金曜日は楽しみです。"],
           notes: nil
       ),
       Vocabulary(
           meaning: "Saturday",
           romaji: "doyoubi",
           hiragana: "どようび",
           katakana: "ドヨウビ",
           kanji: "土曜日",
           word: "土曜日",
           partOfSpeech: "Noun",
           category: .calendar,
           level: 5,
           examples: ["土曜日は映画を見ます。"],
           notes: nil
       ),
       Vocabulary(
          meaning: "January",
          romaji: "ichigatsu",
          hiragana: "いちがつ",
          katakana: "イチガツ",
          kanji: "一月",
          word: "一月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["一月は寒いです。"],
          notes: nil
       ),
       Vocabulary(
          meaning: "February",
          romaji: "nigatsu",
          hiragana: "にがつ",
          katakana: "ニガツ",
          kanji: "二月",
          word: "二月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["二月は春が近づきます。"],
          notes: nil
       ),
       Vocabulary(
          meaning: "March",
          romaji: "sangatsu",
          hiragana: "さんがつ",
          katakana: "サンガツ",
          kanji: "三月",
          word: "三月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["三月は桜が咲きます。"],
          notes: nil
       ),
       Vocabulary(
          meaning: "April",
          romaji: "shigatsu",
          hiragana: "しがつ",
          katakana: "シガツ",
          kanji: "四月",
          word: "四月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["四月に学校が始まります。"],
          notes: nil
       ),
       Vocabulary(
          meaning: "May",
          romaji: "gogatsu",
          hiragana: "ごがつ",
          katakana: "ゴガツ",
          kanji: "五月",
          word: "五月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["五月は気候が良いです。"],
          notes: nil
       ),
       Vocabulary(
          meaning: "June",
          romaji: "rokugatsu",
          hiragana: "ろくがつ",
          katakana: "ロクガツ",
          kanji: "六月",
          word: "六月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["六月は梅雨です。"],
          notes: nil
       ),
       Vocabulary(
          meaning: "July",
          romaji: "shichigatsu",
          hiragana: "しちがつ",
          katakana: "シチガツ",
          kanji: "七月",
          word: "七月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["七月は暑くなります。"],
          notes: nil
       ),
       Vocabulary(
          meaning: "August",
          romaji: "hachigatsu",
          hiragana: "はちがつ",
          katakana: "ハチガツ",
          kanji: "八月",
          word: "八月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["八月は夏休みです。"],
          notes: nil
       ),
       Vocabulary(
          meaning: "September",
          romaji: "kugatsu",
          hiragana: "くがつ",
          katakana: "クガツ",
          kanji: "九月",
          word: "九月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["九月は秋になります。"],
          notes: nil
       ),
       Vocabulary(
          meaning: "October",
          romaji: "juugatsu",
          hiragana: "じゅうがつ",
          katakana: "ジュウガツ",
          kanji: "十月",
          word: "十月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["十月は紅葉がきれいです。"],
          notes: nil
       ),
       Vocabulary(
          meaning: "November",
          romaji: "juuichigatsu",
          hiragana: "じゅういちがつ",
          katakana: "ジュウイチガツ",
          kanji: "十一月",
          word: "十一月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["十一月は涼しくなります。"],
          notes: nil
       ),
       Vocabulary(
          meaning: "December",
          romaji: "juunigatsu",
          hiragana: "じゅうにがつ",
          katakana: "ジュウニガツ",
          kanji: "十二月",
          word: "十二月",
          partOfSpeech: "Noun",
          category: .calendar,
          level: 5,
          examples: ["十二月はクリスマスです。"],
          notes: nil
       )
    ]
   
   static func getVocabulary(category: Vocabulary.Category? = nil) -> [Vocabulary] {
       guard let category = category else { return vocabulary }
       return vocabulary.filter { $0.category == category }
   }
}
